export const STRINGS = {
  extensionTitle: 'ウィッシュリスト',
  content: {
    add: 'ウィッシュリストに追加',
    saved: '保存済み',
    adding: '追加中...',
    removing: '更新中...',
    retry: '再試行',
    unsupported: 'このページでは追加できません',
    addedToast: 'ウィッシュリストに追加しました',
    duplicateToast: 'すでに保存されています',
    removedToast: 'ウィッシュリストから削除しました',
    errorToast: '保存に失敗しました'
  },
  popup: {
    searchPlaceholder: 'アプリ名・開発者・タグ・メモで検索',
    emptyTitle: 'まだウィッシュリストは空です',
    emptyDescription: 'App Store のアプリ詳細ページで追加できます',
    noResultsTitle: '一致するアプリが見つかりません',
    noResultsDescription: '検索条件や並び順を変更して再度お試しください',
    open: '開く',
    edit: '編集',
    save: '保存',
    cancel: 'キャンセル',
    remove: '削除',
    reload: '再読み込み',
    loadError: 'データの読み込みに失敗しました',
    footerOptions: '設定',
    footerExport: '書き出し',
    noteLabel: 'メモ',
    tagsLabel: 'タグ',
    notePlaceholder: 'このアプリを後で見返すためのメモを残せます',
    tagsPlaceholder: 'タグをカンマ区切りで入力',
    editDialogTitle: 'メモとタグを編集',
    saveSuccess: 'メモとタグを保存しました'
  },
  options: {
    title: '設定',
    basicSettings: '基本設定',
    dataManagement: 'データ管理',
    displaySettings: '表示設定',
    debugInfo: 'デバッグ情報',
    versionInfo: 'バージョン情報',
    export: 'JSON を書き出す',
    import: 'JSON を読み込む',
    clearAll: '全件削除',
    confirmDeleteAll: '保存済みデータをすべて削除します。よろしいですか？',
    confirmDeleteOne: 'このアプリを削除しますか？',
    importSuccess: 'インポートが完了しました',
    importFailure: 'インポートに失敗しました',
    saveSuccess: '設定を保存しました',
    saveFailure: '設定の保存に失敗しました'
  }
} as const;
